---
- alias: Users
  username: testUser
  email: testUser@test.com
  home:
    dir:
      override: local/root/run/
  accept:
    password: testpass
  actions:
    collect:
      alias: connectTest
      commands:
      - GET -DEL *
      - LCOPY -REC %inbox% %inbox%/in
- alias: Users
  username: testUser2
  email: testUser2@test.com
  home:
    dir:
      override: local/root/run/
  accept:
    password: testpass
  actions:
    collect:
      alias: connectTest
      commands:
      - GET -DEL *
      - LCOPY -REC %inbox% %inbox%/in
